// config.js — auto-generated by the UI
export default {
  baseURL: "https://books.toscrape.com",
  crawl: {
    maxPages: 8,
    maxDepth: 2,
    waitAfterAction: 500,
    seedPaths: [
      "/catalogue/a-light-in-the-attic_1000/index.html"
    ]
  },
  auth: { type: "none" },
  output: {
    rawDir: "tests/generated/site-maps/raw",
    summaryFile: "tests/generated/site-maps/crawl-summary.json"
  }
};
