// server/index.js
import express from "express";
import cors from "cors";
import fs from "fs";
import path from "path";
import { spawn } from "child_process";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");

const app = express();
app.use(cors());
app.use(express.json());

// ---- Crawl state ----
let crawlState = { status: "idle", logs: [], error: null };
let sseClients = [];

function broadcast(line) {
  crawlState.logs.push(line);
  const data = `data: ${JSON.stringify({ line })}\n\n`;
  sseClients.forEach((res) => res.write(data));
}

function writeConfig(settings) {
  const { baseURL, auth, maxPages, maxDepth, seedPaths } = settings;
  const authBlock = buildAuthBlock(auth);
  const parsedSeedPaths = seedPaths
    ? seedPaths.split("\n").map(p => p.trim()).filter(p => p.startsWith("/"))
    : [];

  const content = `// config.js — auto-generated by the UI
export default {
  baseURL: ${JSON.stringify(baseURL)},
  crawl: {
    maxPages: ${maxPages || 30},
    maxDepth: ${maxDepth || 5},
    waitAfterAction: 500,
    seedPaths: ${JSON.stringify(parsedSeedPaths)}
  },
  auth: ${authBlock},
  output: {
    rawDir: "tests/generated/site-maps/raw",
    summaryFile: "tests/generated/site-maps/crawl-summary.json"
  }
};
`;
  fs.writeFileSync(path.join(ROOT, "config.js"), content, "utf-8");
}

function buildAuthBlock(auth) {
  if (!auth || auth.type === "none") return `{ type: "none" }`;
  if (auth.type === "form") {
    return `{
    type: "form",
    loginURL: ${JSON.stringify(auth.loginURL || "/login")},
    usernameSelector: ${JSON.stringify(auth.usernameSelector || "#email")},
    passwordSelector: ${JSON.stringify(auth.passwordSelector || "#password")},
    submitSelector: ${JSON.stringify(auth.submitSelector || "#login-button")},
    username: process.env.TEST_USERNAME || ${JSON.stringify(auth.username || "")},
    password: process.env.TEST_PASSWORD || ${JSON.stringify(auth.password || "")},
    successURLContains: ${JSON.stringify(auth.successURLContains || "/dashboard")}
  }`;
  }
  if (auth.type === "bearer") {
    return `{
    type: "bearer",
    bearerToken: process.env.TEST_BEARER_TOKEN || ${JSON.stringify(auth.bearerToken || "")}
  }`;
  }
  if (auth.type === "cookie") {
    return `{
    type: "cookie",
    cookie: {
      name: ${JSON.stringify(auth.cookieName || "session_id")},
      value: process.env.TEST_SESSION_COOKIE || ${JSON.stringify(auth.cookieValue || "")},
      domain: ${JSON.stringify(auth.cookieDomain || "")}
    }
  }`;
  }
  return `{ type: "none" }`;
}

function writeFuzzConfig(baseURL) {
  const content = `// config.js — auto-generated by fuzzer UI
export default {
  baseURL: ${JSON.stringify(baseURL)},
  crawl: {
    maxPages: 30,
    maxDepth: 5,
    waitAfterAction: 500,
    seedPaths: []
  },
  auth: { type: "none" },
  output: {
    rawDir: "tests/generated/site-maps/raw",
    summaryFile: "tests/generated/site-maps/crawl-summary.json"
  }
};
`;
  fs.writeFileSync(path.join(ROOT, "config.js"), content, "utf-8");
}

// ---- Crawl routes ----
app.post("/api/crawl", (req, res) => {
  if (crawlState.status === "crawling") {
    return res.status(409).json({ error: "A crawl is already running" });
  }
  const settings = req.body;
  if (!settings.baseURL) {
    return res.status(400).json({ error: "baseURL is required" });
  }
  crawlState = { status: "crawling", logs: [], error: null };
  try {
    writeConfig(settings);
  } catch (err) {
    crawlState.status = "error";
    return res.status(500).json({ error: err.message });
  }
  const child = spawn("node", ["crawler/index.js"], { cwd: ROOT, env: { ...process.env } });
  child.stdout.on("data", (data) => data.toString().split("\n").filter(Boolean).forEach(broadcast));
  child.stderr.on("data", (data) => data.toString().split("\n").filter(Boolean).forEach((l) => broadcast(`[stderr] ${l}`)));
  child.on("close", (code) => {
    crawlState.status = code === 0 ? "done" : "error";
    broadcast(code === 0 ? "[crawl complete]" : `[crawl failed: exit code ${code}]`);
    sseClients.forEach((c) => c.write(`event: done\ndata: ${JSON.stringify({ status: crawlState.status })}\n\n`));
    sseClients = [];
  });
  res.json({ message: "Crawl started" });
});

app.get("/api/crawl/stream", (req, res) => {
  res.setHeader("Content-Type", "text/event-stream");
  res.setHeader("Cache-Control", "no-cache");
  res.setHeader("Connection", "keep-alive");
  res.flushHeaders();
  crawlState.logs.forEach((line) => res.write(`data: ${JSON.stringify({ line })}\n\n`));
  if (crawlState.status === "done" || crawlState.status === "error") {
    res.write(`event: done\ndata: ${JSON.stringify({ status: crawlState.status })}\n\n`);
    res.end();
    return;
  }
  sseClients.push(res);
  req.on("close", () => { sseClients = sseClients.filter((c) => c !== res); });
});

app.get("/api/crawl/status", (req, res) => {
  res.json({ status: crawlState.status, logCount: crawlState.logs.length, error: crawlState.error });
});

app.get("/api/sitemap", (req, res) => {
  const rawDir = path.join(ROOT, "tests/generated/site-maps/raw");
  const summaryFile = path.join(ROOT, "tests/generated/site-maps/crawl-summary.json");
  if (!fs.existsSync(summaryFile)) {
    return res.status(404).json({ error: "No crawl data found. Run a crawl first." });
  }
  const summary = JSON.parse(fs.readFileSync(summaryFile, "utf-8"));
  const pages = [];
  if (fs.existsSync(rawDir)) {
    fs.readdirSync(rawDir).filter((f) => f.endsWith(".json")).forEach((file) => {
      try { pages.push(JSON.parse(fs.readFileSync(path.join(rawDir, file), "utf-8"))); } catch {}
    });
  }
  res.json({ summary, pages });
});

// ---- Generator state ----
let generateState = { status: "idle", logs: [], error: null };
let generateClients = [];

function broadcastGenerate(line) {
  generateState.logs.push(line);
  const data = `data: ${JSON.stringify({ line })}\n\n`;
  generateClients.forEach((res) => res.write(data));
}

app.post("/api/generate", (req, res) => {
  if (generateState.status === "running") {
    return res.status(409).json({ error: "Generator is already running" });
  }
  generateState = { status: "running", logs: [], error: null };
  const child = spawn("node", ["generator/index.js"], { cwd: ROOT, env: { ...process.env } });
  child.stdout.on("data", (data) => data.toString().split("\n").filter(Boolean).forEach(broadcastGenerate));
  child.stderr.on("data", (data) => data.toString().split("\n").filter(Boolean).forEach((l) => broadcastGenerate(`[stderr] ${l}`)));
  child.on("close", (code) => {
    generateState.status = code === 0 ? "done" : "error";
    broadcastGenerate(code === 0 ? "[generate complete]" : `[generate failed: exit code ${code}]`);
    generateClients.forEach((c) => c.write(`event: done\ndata: ${JSON.stringify({ status: generateState.status })}\n\n`));
    generateClients = [];
  });
  res.json({ message: "Generator started" });
});

app.get("/api/generate/stream", (req, res) => {
  res.setHeader("Content-Type", "text/event-stream");
  res.setHeader("Cache-Control", "no-cache");
  res.setHeader("Connection", "keep-alive");
  res.flushHeaders();
  generateState.logs.forEach((line) => res.write(`data: ${JSON.stringify({ line })}\n\n`));
  if (generateState.status === "done" || generateState.status === "error") {
    res.write(`event: done\ndata: ${JSON.stringify({ status: generateState.status })}\n\n`);
    res.end();
    return;
  }
  generateClients.push(res);
  req.on("close", () => { generateClients = generateClients.filter((c) => c !== res); });
});

app.get("/api/generator/results", (req, res) => {
  const casesDir = path.join(ROOT, "tests/generated/test-cases");
  const dataDir = path.join(ROOT, "tests/generated/test-data");
  const specsDir = path.join(ROOT, "tests/generated/specs");
  const results = { cases: [], data: [], specs: [] };
  if (fs.existsSync(casesDir)) {
    fs.readdirSync(casesDir).filter((f) => f.endsWith(".json")).forEach((file) => {
      try { results.cases.push(JSON.parse(fs.readFileSync(path.join(casesDir, file), "utf-8"))); } catch {}
    });
  }
  if (fs.existsSync(dataDir)) {
    fs.readdirSync(dataDir).filter((f) => f.endsWith(".json")).forEach((file) => {
      try { results.data.push(JSON.parse(fs.readFileSync(path.join(dataDir, file), "utf-8"))); } catch {}
    });
  }
  if (fs.existsSync(specsDir)) {
    fs.readdirSync(specsDir).filter((f) => f.endsWith(".js")).forEach((file) => {
      try {
        results.specs.push({ filename: file, content: fs.readFileSync(path.join(specsDir, file), "utf-8") });
      } catch {}
    });
  }
  res.json(results);
});

// ---- Standalone data regeneration ----
app.post("/api/generate-data", async (req, res) => {
  try {
    const { generateTestData } = await import("../generator/data.js");
    const casesDir = path.join(ROOT, "tests/generated/test-cases");
    const dataDir = path.join(ROOT, "tests/generated/test-data");
    const rawDir = path.join(ROOT, "tests/generated/site-maps/raw");

    if (!fs.existsSync(casesDir)) {
      return res.status(400).json({ error: "No test cases found. Run the generator first." });
    }

    const allCases = {};
    fs.readdirSync(casesDir).filter(f => f.endsWith(".json")).forEach(file => {
      try {
        const data = JSON.parse(fs.readFileSync(path.join(casesDir, file), "utf-8"));
        allCases[data.feature] = data.cases;
      } catch {}
    });

    const allData = generateTestData(allCases, rawDir);

    fs.mkdirSync(dataDir, { recursive: true });
    for (const [feature, cases] of Object.entries(allCases)) {
      const featureData = {};
      cases.forEach(tc => { if (allData[tc.id]) featureData[tc.id] = allData[tc.id]; });
      const filename = feature.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "") + ".data.json";
      fs.writeFileSync(path.join(dataDir, filename), JSON.stringify({ feature, data: featureData }, null, 2));
    }

    res.json({
      message: "Test data regenerated",
      count: Object.keys(allData).filter(k => allData[k] !== null).length
    });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ---- Runner state ----
let runnerState = { status: "idle", logs: [], error: null };
let runnerClients = [];

function broadcastRunner(line) {
  runnerState.logs.push(line);
  const data = `data: ${JSON.stringify({ line })}\n\n`;
  runnerClients.forEach((res) => res.write(data));
}

app.post("/api/run-tests", (req, res) => {
  if (runnerState.status === "running") {
    return res.status(409).json({ error: "Runner is already running" });
  }
  runnerState = { status: "running", logs: [], error: null };
  const child = spawn("node", ["runner/index.js"], { cwd: ROOT, env: { ...process.env } });
  child.stdout.on("data", (data) => data.toString().split("\n").filter(Boolean).forEach(broadcastRunner));
  child.stderr.on("data", (data) => data.toString().split("\n").filter(Boolean).forEach((l) => broadcastRunner(`[stderr] ${l}`)));
  child.on("close", (code) => {
    runnerState.status = code === 0 ? "done" : "error";
    broadcastRunner(code === 0 ? "[tests complete]" : `[tests failed: exit code ${code}]`);
    runnerClients.forEach((c) => c.write(`event: done\ndata: ${JSON.stringify({ status: runnerState.status })}\n\n`));
    runnerClients = [];
  });
  res.json({ message: "Runner started" });
});

app.post("/api/run-improved", (req, res) => {
  if (runnerState.status === "running") {
    return res.status(409).json({ error: "Runner is already running" });
  }
  runnerState = { status: "running", logs: [], error: null };
  const child = spawn("node", ["runner/index.js", "--specs-dir", "tests/generated/improved"], { cwd: ROOT, env: { ...process.env } });
  child.stdout.on("data", (data) => data.toString().split("\n").filter(Boolean).forEach(broadcastRunner));
  child.stderr.on("data", (data) => data.toString().split("\n").filter(Boolean).forEach((l) => broadcastRunner(`[stderr] ${l}`)));
  child.on("close", (code) => {
    runnerState.status = code === 0 ? "done" : "error";
    broadcastRunner(code === 0 ? "[tests complete]" : `[tests failed: exit code ${code}]`);
    runnerClients.forEach((c) => c.write(`event: done\ndata: ${JSON.stringify({ status: runnerState.status })}\n\n`));
    runnerClients = [];
  });
  res.json({ message: "Improved runner started" });
});

app.get("/api/run-tests/stream", (req, res) => {
  res.setHeader("Content-Type", "text/event-stream");
  res.setHeader("Cache-Control", "no-cache");
  res.setHeader("Connection", "keep-alive");
  res.flushHeaders();
  runnerState.logs.forEach((line) => res.write(`data: ${JSON.stringify({ line })}\n\n`));
  if (runnerState.status === "done" || runnerState.status === "error") {
    res.write(`event: done\ndata: ${JSON.stringify({ status: runnerState.status })}\n\n`);
    res.end();
    return;
  }
  runnerClients.push(res);
  req.on("close", () => { runnerClients = runnerClients.filter((c) => c !== res); });
});

app.get("/api/runner/status", (req, res) => {
  res.json({ status: runnerState.status });
});

app.post("/api/report", async (req, res) => {
  try {
    const { generateReport } = await import("../runner/reporter.js");
    const report = await generateReport(false);
    res.json({ report });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.post("/api/improved-report", async (req, res) => {
  try {
    const { generateImprovedReport } = await import("../runner/reporter.js");
    const report = await generateImprovedReport(false);
    res.json({ report });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.get("/api/report/results", (req, res) => {
  const resultsFile = path.join(ROOT, "tests/generated/reports/results.json");
  const reportFile = path.join(ROOT, "tests/generated/reports/bug_report.md");
  if (!fs.existsSync(resultsFile)) {
    return res.status(404).json({ error: "No results found. Run tests first." });
  }
  const results = JSON.parse(fs.readFileSync(resultsFile, "utf-8"));
  const report = fs.existsSync(reportFile) ? fs.readFileSync(reportFile, "utf-8") : null;
  res.json({ results, report });
});

// ---- Fuzzer state ----
let fuzzState = { status: "idle", logs: [], error: null };
let fuzzClients = [];

function broadcastFuzz(line) {
  fuzzState.logs.push(line);
  const data = `data: ${JSON.stringify({ line })}\n\n`;
  fuzzClients.forEach((res) => res.write(data));
}

app.post("/api/fuzz", (req, res) => {
  if (fuzzState.status === "running") {
    return res.status(409).json({ error: "Fuzzer is already running" });
  }
  const { baseURL } = req.body || {};
  if (baseURL) {
    try {
      writeFuzzConfig(baseURL);
      console.log(`Fuzzer config updated: ${baseURL}`);
    } catch (err) {
      return res.status(500).json({ error: `Failed to update config: ${err.message}` });
    }
  }
  fuzzState = { status: "running", logs: [], error: null };
  const child = spawn("node", ["fuzzer/index.js"], { cwd: ROOT, env: { ...process.env } });
  child.stdout.on("data", (data) => data.toString().split("\n").filter(Boolean).forEach(broadcastFuzz));
  child.stderr.on("data", (data) => data.toString().split("\n").filter(Boolean).forEach((l) => broadcastFuzz(`[stderr] ${l}`)));
  child.on("close", (code) => {
    fuzzState.status = code === 0 ? "done" : "error";
    broadcastFuzz(code === 0 ? "[fuzz complete]" : `[fuzz failed: exit code ${code}]`);
    fuzzClients.forEach((c) => c.write(`event: done\ndata: ${JSON.stringify({ status: fuzzState.status })}\n\n`));
    fuzzClients = [];
  });
  res.json({ message: "Fuzzer started" });
});

app.get("/api/fuzz/stream", (req, res) => {
  res.setHeader("Content-Type", "text/event-stream");
  res.setHeader("Cache-Control", "no-cache");
  res.setHeader("Connection", "keep-alive");
  res.flushHeaders();
  fuzzState.logs.forEach((line) => res.write(`data: ${JSON.stringify({ line })}\n\n`));
  if (fuzzState.status === "done" || fuzzState.status === "error") {
    res.write(`event: done\ndata: ${JSON.stringify({ status: fuzzState.status })}\n\n`);
    res.end();
    return;
  }
  fuzzClients.push(res);
  req.on("close", () => { fuzzClients = fuzzClients.filter((c) => c !== res); });
});

app.get("/api/fuzz/results", (req, res) => {
  const resultsFile = path.join(ROOT, "tests/generated/fuzz/reports/fuzz_results.json");
  const reportFile = path.join(ROOT, "tests/generated/fuzz/reports/fuzz_report.md");
  if (!fs.existsSync(resultsFile)) {
    return res.status(404).json({ error: "No fuzz results found. Run the fuzzer first." });
  }
  const results = JSON.parse(fs.readFileSync(resultsFile, "utf-8"));
  const report = fs.existsSync(reportFile) ? fs.readFileSync(reportFile, "utf-8") : null;
  res.json({ results, report });
});

app.get("/api/fuzz/files", (req, res) => {
  const casesFile = path.join(ROOT, "tests/generated/fuzz/test-cases/fuzz.cases.json");
  const dataFile = path.join(ROOT, "tests/generated/fuzz/test-data/fuzz.data.json");
  const specFile = path.join(ROOT, "tests/generated/fuzz/specs/fuzz.spec.js");
  if (!fs.existsSync(casesFile)) {
    return res.status(404).json({ error: "No fuzz files found." });
  }
  const casesData = JSON.parse(fs.readFileSync(casesFile, "utf-8"));
  const dataData = fs.existsSync(dataFile) ? JSON.parse(fs.readFileSync(dataFile, "utf-8")) : { data: {} };
  const spec = fs.existsSync(specFile) ? fs.readFileSync(specFile, "utf-8") : null;
  res.json({ cases: casesData.cases || [], data: dataData.data || {}, spec });
});

// ---- Frontend Fuzzer state ----
let fuzzFrontendState = { status: "idle", logs: [], error: null };
let fuzzFrontendClients = [];

function broadcastFuzzFrontend(line) {
  fuzzFrontendState.logs.push(line);
  const data = `data: ${JSON.stringify({ line })}\n\n`;
  fuzzFrontendClients.forEach((res) => res.write(data));
}

app.post("/api/fuzz-frontend", (req, res) => {
  if (fuzzFrontendState.status === "running") {
    return res.status(409).json({ error: "Frontend fuzzer is already running" });
  }
  fuzzFrontendState = { status: "running", logs: [], error: null };
  const child = spawn("node", ["fuzzer/form-runner.js"], { cwd: ROOT, env: { ...process.env } });
  child.stdout.on("data", (data) => data.toString().split("\n").filter(Boolean).forEach(broadcastFuzzFrontend));
  child.stderr.on("data", (data) => data.toString().split("\n").filter(Boolean).forEach((l) => broadcastFuzzFrontend(`[stderr] ${l}`)));
  child.on("close", (code) => {
    fuzzFrontendState.status = code === 0 ? "done" : "error";
    broadcastFuzzFrontend(code === 0 ? "[frontend fuzz complete]" : `[frontend fuzz failed: exit code ${code}]`);
    fuzzFrontendClients.forEach((c) => c.write(`event: done\ndata: ${JSON.stringify({ status: fuzzFrontendState.status })}\n\n`));
    fuzzFrontendClients = [];
  });
  res.json({ message: "Frontend fuzzer started" });
});

app.get("/api/fuzz-frontend/stream", (req, res) => {
  res.setHeader("Content-Type", "text/event-stream");
  res.setHeader("Cache-Control", "no-cache");
  res.setHeader("Connection", "keep-alive");
  res.flushHeaders();
  fuzzFrontendState.logs.forEach((line) => res.write(`data: ${JSON.stringify({ line })}\n\n`));
  if (fuzzFrontendState.status === "done" || fuzzFrontendState.status === "error") {
    res.write(`event: done\ndata: ${JSON.stringify({ status: fuzzFrontendState.status })}\n\n`);
    res.end();
    return;
  }
  fuzzFrontendClients.push(res);
  req.on("close", () => { fuzzFrontendClients = fuzzFrontendClients.filter((c) => c !== res); });
});

app.get("/api/fuzz-frontend/results", (req, res) => {
  const resultsFile = path.join(ROOT, "tests/generated/fuzz/reports/fuzz_form_results.json");
  const reportFile = path.join(ROOT, "tests/generated/fuzz/reports/fuzz_form_report.md");
  if (!fs.existsSync(resultsFile)) {
    return res.status(404).json({ error: "No frontend fuzz results found. Run Fuzz Frontend first." });
  }
  const results = JSON.parse(fs.readFileSync(resultsFile, "utf-8"));
  const report = fs.existsSync(reportFile) ? fs.readFileSync(reportFile, "utf-8") : null;
  res.json({ results, report });
});

// ---- Improver state ----
let improveState = { status: "idle", logs: [], error: null };
let improveClients = [];

function broadcastImprove(line) {
  improveState.logs.push(line);
  const data = `data: ${JSON.stringify({ line })}\n\n`;
  improveClients.forEach((res) => res.write(data));
}

app.post("/api/improve-tests", (req, res) => {
  if (improveState.status === "running") {
    return res.status(409).json({ error: "Improver is already running" });
  }
  improveState = { status: "running", logs: [], error: null };
  const child = spawn("node", ["generator/index.js", "--improve", "--source", "runner"], { cwd: ROOT, env: { ...process.env } });
  child.stdout.on("data", (data) => data.toString().split("\n").filter(Boolean).forEach(broadcastImprove));
  child.stderr.on("data", (data) => data.toString().split("\n").filter(Boolean).forEach((l) => broadcastImprove(`[stderr] ${l}`)));
  child.on("close", (code) => {
    improveState.status = code === 0 ? "done" : "error";
    broadcastImprove(code === 0 ? "[improve complete]" : `[improve failed: exit code ${code}]`);
    improveClients.forEach((c) => c.write(`event: done\ndata: ${JSON.stringify({ status: improveState.status })}\n\n`));
    improveClients = [];
  });
  res.json({ message: "Improver started" });
});

app.post("/api/improve-fuzz", (req, res) => {
  if (improveState.status === "running") {
    return res.status(409).json({ error: "Improver is already running" });
  }
  improveState = { status: "running", logs: [], error: null };
  const child = spawn("node", ["generator/index.js", "--improve", "--source", "fuzzer"], { cwd: ROOT, env: { ...process.env } });
  child.stdout.on("data", (data) => data.toString().split("\n").filter(Boolean).forEach(broadcastImprove));
  child.stderr.on("data", (data) => data.toString().split("\n").filter(Boolean).forEach((l) => broadcastImprove(`[stderr] ${l}`)));
  child.on("close", (code) => {
    improveState.status = code === 0 ? "done" : "error";
    broadcastImprove(code === 0 ? "[improve complete]" : `[improve failed: exit code ${code}]`);
    improveClients.forEach((c) => c.write(`event: done\ndata: ${JSON.stringify({ status: improveState.status })}\n\n`));
    improveClients = [];
  });
  res.json({ message: "Fuzzer improver started" });
});

app.get("/api/improve-tests/stream", (req, res) => {
  res.setHeader("Content-Type", "text/event-stream");
  res.setHeader("Cache-Control", "no-cache");
  res.setHeader("Connection", "keep-alive");
  res.flushHeaders();
  improveState.logs.forEach((line) => res.write(`data: ${JSON.stringify({ line })}\n\n`));
  if (improveState.status === "done" || improveState.status === "error") {
    res.write(`event: done\ndata: ${JSON.stringify({ status: improveState.status })}\n\n`);
    res.end();
    return;
  }
  improveClients.push(res);
  req.on("close", () => { improveClients = improveClients.filter((c) => c !== res); });
});

app.get("/api/improve-tests/results", (req, res) => {
  const resultsFile = path.join(ROOT, "tests/generated/improved/improved_run_results.json");
  const metaFile = path.join(ROOT, "tests/generated/improved/improved_meta.json");
  const specFile = path.join(ROOT, "tests/generated/improved/improved.spec.js");
  const reportFile = path.join(ROOT, "tests/generated/improved/improved_report.md");

  if (!fs.existsSync(resultsFile) && !fs.existsSync(metaFile)) {
    return res.status(404).json({ error: "No improved test results found. Run Improve Tests first." });
  }

  const results = fs.existsSync(resultsFile) ? JSON.parse(fs.readFileSync(resultsFile, "utf-8")) : [];
  const meta = fs.existsSync(metaFile) ? JSON.parse(fs.readFileSync(metaFile, "utf-8")) : [];
  const spec = fs.existsSync(specFile) ? fs.readFileSync(specFile, "utf-8") : null;
  const report = fs.existsSync(reportFile) ? fs.readFileSync(reportFile, "utf-8") : null;

  res.json({ results, meta, spec, report });
});

// ---- Start ----
const PORT = 3001;
app.listen(PORT, () => console.log(`Backend server running at http://localhost:${PORT}`));